version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      DOCKERIZED: "true"

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
